### ISSUE TITLE
Multi-Click event lost when the latest press/release time didn't fit into the time window.

### ISSUE THREAD

**Issue by YesYeu** [MaJerle/lwbtn#2]
Multi-Click event lost when the latest press/release time didn't fit into the time window.

Code Version:         v1.0.0

Test Case:

Part of test.c :
```
/*
 * Simulate click event
 */
static const btn_test_time_t test_sequence[] = {
    BTN_STATE(1, LWBTN_CFG_TIME_DEBOUNCE_PRESS + LWBTN_CFG_TIME_CLICK_MIN),
    BTN_STATE(0, LWBTN_CFG_TIME_DEBOUNCE_RELEASE + LWBTN_CFG_TIME_CLICK_MAX),
    BTN_STATE(1, LWBTN_CFG_TIME_DEBOUNCE_PRESS + LWBTN_CFG_TIME_CLICK_MIN / 2), 
    BTN_STATE(0, LWBTN_CFG_TIME_DEBOUNCE_RELEASE + LWBTN_CFG_TIME_CLICK_MULTI_MAX + 1),
    BTN_STATE(0, 100)
};

/* List of expected test events during different input states and their timings */
static const btn_test_evt_t test_events[] = {
    BTN_EVENT_ONPRESS(),
    BTN_EVENT_ONRELEASE(),
    BTN_EVENT_ONPRESS(),
    BTN_EVENT_ONRELEASE(),
};
```

Part of lwbtn_opt.h :
```
#define LWBTN_CFG_TIME_CLICK_MIN 20
#define LWBTN_CFG_TIME_CLICK_MAX 300
#define LWBTN_CFG_TIME_CLICK_MULTI_MAX 400
#define LWBTN_CFG_CLICK_MAX_CONSECUTIVE 3
#define LWBTN_CFG_CLICK_MAX_CONSECUTIVE_SEND_IMMEDIATELY 1
```

Running result（On Win10）:
```
Test running
[     20][    20] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   0
[     42][    22] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   0
[    361][   319] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   1
[    372][    11] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   1
```

No ONCLICK event is reported.   Notice that the lasting time of active state in second click is LWBTN_CFG_TIME_CLICK_MIN / 2, which is smaller than LWBTN_CFG_TIME_CLICK_MIN .   

I find it results from the following code in lwbtn.c:
```
 /* Check time validity for click event */
if ((mstime - btn->time_change) >= LWBTN_TIME_CLICK_GET_PRESSED_MIN(btn)
    && (mstime - btn->time_change) <= LWBTN_TIME_CLICK_GET_PRESSED_MAX(btn)) {
     /*  ... ...  */
     } else {
           /*
            * There was an on-release event, but timing
            * for click event detection is outside allowed window.
            * 
            * Reset clicks counter -> not valid sequence for click event.
            */
            btn->click.cnt = 0;      /* click.cnt is cleared here so no On-Click event will be triggered in our test case. */
}

```
Does this behaviour conform with the consideration of design and why?
 Or to say, should we ignore the precedent valid clicks just because the latest press/release is invalid (beyond the window defined by LWBTN_CFG_TIME_CLICK_MIN  and LWBTN_CFG_TIME_CLICK_MAX )?

**Comment by MaJerle** [comment]
> Does this behavior conform with the consideration of design and why?

Very good question. At some point, it makes sense that if you have a sequence of clicks, and last one is too short, the sequence shall be considered invalid. 

> Or to say, should we ignore the precedent valid clicks just because the latest press/release is invalid (beyond the window defined by LWBTN_CFG_TIME_CLICK_MIN and LWBTN_CFG_TIME_CLICK_MAX )?

That was original intent. But, now that you mention it, we may add a macro, that would anyway send the status before clicks event is reset. But also to ask, how should be the sequence of events in your test program?

Today you got:
```
Test running
[     20][    20] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   0
[     42][    22] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   0
[    361][   319] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   1
[    372][    11] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   1
```

Should it be
```
Test running
[     20][    20] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   0
[     42][    22] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   0
[    361][   319] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   1
[    372][    11] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   1
[    372][    11] evt: ONCLICK, keep-alive cnt:   0, click cnt:   1
```
or
```
Test running
[     20][    20] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   0
[     42][    22] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   0
[    361][   319] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   1
[    372][    11] evt: ONCLICK, keep-alive cnt:   0, click cnt:   1
[    372][    11] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   1
```

This seems to be the code you are referring to: https://github.com/MaJerle/lwbtn/blob/2e16fbe6b5f498bf9c613ca997edf128983f520b/lwbtn/src/lwbtn/lwbtn.c#L229-L235

**Comment by YesYeu** [comment]
> But also to ask, how should be the sequence of events in your test program?



Since the click time window is checked  after triggering  ONRELEASE event(see https://github.com/MaJerle/lwbtn/blob/2e16fbe6b5f498bf9c613ca997edf128983f520b/lwbtn/src/lwbtn/lwbtn.c#L198-L203)， I prefer the following test events， personally：
```
/* List of expected test events during different input states and their timings */
static const btn_test_evt_t test_events[] = {
    BTN_EVENT_ONPRESS(),
    BTN_EVENT_ONRELEASE(),
    BTN_EVENT_ONPRESS(),
    BTN_EVENT_ONRELEASE(),
    BTN_EVENT_ONCLICK(1)
};
```

And
https://github.com/MaJerle/lwbtn/blob/2e16fbe6b5f498bf9c613ca997edf128983f520b/lwbtn/src/lwbtn/lwbtn.c#L229-L235
This code can be modified to：
```
                    /*
                     * There was an on-release event, but timing
                     * for click event detection is outside allowed window.
                     * 
                     * Reset clicks counter -> not valid sequence for click event.
                     */
                    if (btn->click.cnt > 0) {
                            lwobj->evt_fn(lwobj, btn, LWBTN_EVT_ONCLICK);
                    }
                    btn->click.cnt = 0;            
```

This new code passes the test case.
```
Test running
[     20][    20] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   0
[     42][    22] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   0
[    361][   319] evt:   ONPRESS, keep-alive cnt:   0, click cnt:   1
[    372][    11] evt: ONRELEASE, keep-alive cnt:   0, click cnt:   1
[    372][    11] evt: ONCLICK, keep-alive cnt:   0, click cnt:   1
```

**Comment by MaJerle** [comment]
This code can only be added under the conditional compilation. Otherwise, the whole purpose is that if you do CLICK+CLICK+LONG-PRESS, then you do not want a click event, to occur.

Potentially, we can have different conditions for click being too short or click being too long, but in both cases it must be with conditional compilation, or having an option for dynamic configuration, to distinguish between buttons.

I will think about it, how to implement it best way to cover use cases.
